Fixed population after rename
anno-assist/anno-assist.github.io pull request #2
Opened 2023-05-10 07:01 UTC by vassdeniss

When renaming an island, the population gets lost locally, so the population needs to be updated after the island url rename.

2023-05-11 08:01 UTC, viktorpts requested changes

2023-05-11 08:01 UTC, viktorpts commented on src/views/islands.js
> +            population[island.url] = population[oldUrl];
The variable `population` doesn't exist

2023-05-11 08:01 UTC, viktorpts commented on src/views/islands.js
> +            delete ctx.popSettings[oldUrl];
`ctx.popSettings` contains information about calculations and doesn't store information about the current game or islands. Perhaps you meant `ctx.population`?

2023-05-11 08:01 UTC, viktorpts commented on src/views/islands.js
> +            delete popSettings[oldUrl];
Like the previous variable, this one seems to be undeclared.

2023-05-11 08:09 UTC, vassdeniss commented
Sorry about that, I was coding it in my own version of the app which had different variable names in some places.

2023-05-12 13:47 UTC, viktorpts approved these changes

2023-05-12 13:47 UTC, merged